name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_ENV: testing  # Ensure test config is used
          PYTHONPATH: .
        run: pytest --disable-warnings

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures tests pass before building
    if: github.ref == 'refs/heads/main'  # Only run on pushes to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t emelalkim/communication-service:latest .

      - name: Push Docker image to Docker Hub
        run: docker push emelalkim/communication-service:latest

      - name: Deploy Docker container locally with volume
        run: |
          docker run -p 5000:5000 -d \
            -v communication_service_db:/app/db \
            --name communication_service \
            emelalkim/communication-service:latest

      - name: Wait for application to start
        run: |
          for i in {1..10}; do
            if docker logs communication_service 2>&1 | grep "Listening at: http://0.0.0.0:5000"; then
              echo "Application is ready"
              exit 0
            else
              echo "Waiting for application to start..."
              sleep 5
            fi
          done
          echo "Application failed to start in time" && exit 1

      - name: Test Docker container
        run: curl http://localhost:5000/messageLog

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop communication_service || true
            docker rm communication_service || true
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/communication-service:latest
            docker run -p 80:5000 -d -v /home/ubuntu/db:/app/db --name communication_service ${{ vars.DOCKERHUB_USERNAME }}/communication-service:latest
            docker system prune --all --force